<!--====== Jquery js ======-->
<script src="{{ asset('assets/vendor/jquery-3.7.1.min.js') }}"></script>
<!--====== Bootstrap js ======-->
<script src="{{ asset('assets/vendor/popper/popper.min.js') }}"></script>
<!--====== Bootstrap js ======-->
<script src="{{ asset('assets/vendor/bootstrap/js/bootstrap.min.js') }}"></script>
<!--====== Slick js ======-->
<script src="{{ asset('assets/vendor/slick/slick.min.js') }}"></script>
<!--====== Magnific js ======-->
<script src="{{ asset('assets/vendor/magnific-popup/dist/jquery.magnific-popup.min.js') }}"></script>
<!--====== Counterup js ======-->
<script src="{{ asset('assets/vendor/jquery.counterup.min.js') }}"></script>
<!--====== Waypoints js ======-->
<script src="{{ asset('assets/vendor/jquery.waypoints.js') }}"></script>
<!--====== Nice-select js ======-->
<script src="{{ asset('assets/vendor/nice-select/js/jquery.nice-select.min.js') }}"></script>
<!--====== jquery UI js ======-->
<script src="{{ asset('assets/vendor/jquery-ui/jquery-ui.min.js') }}"></script>
<!--====== WOW js ======-->
<script src="{{ asset('assets/vendor/wow.min.js') }}"></script>
<!--====== Main js ======-->
<script src="{{ asset('assets/js/theme.js') }}"></script>
